# Generated by Django 5.1 on 2024-08-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("color", models.CharField(max_length=30)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "transmission",
                    models.CharField(
                        choices=[("A", "Automatic"), ("M", "Manual")], max_length=1
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
